import { mkdir, writeFile } from "node:fs/promises";
import StyleDictionary from "style-dictionary";

/**
 * Token tiers:
 *   src/primitive/*       raw palette & scales (no meaning)
 *   src/semantic/base     role-based aliases that are the same in every theme
 *   src/semantic/<theme>  role-based aliases that change per theme (color, shadow)
 *
 * Every theme is built with its own StyleDictionary instance (the theme files
 * define the same token names), then stitched together into one tokens.css.
 */

const PREFIX = "ds";
const OUT = "dist";
const THEMES = ["light", "dark"];

const isPrimitive = (token) => token.filePath.includes("src/primitive/");
const isThemed = (token) => /src\/semantic\/(light|dark)\.json$/.test(token.filePath);

function createDictionary(theme) {
  return new StyleDictionary({
    source: ["src/primitive/**/*.json", "src/semantic/base.json", `src/semantic/${theme}.json`],
    log: { verbosity: "silent" },
    platforms: {
      css: {
        transformGroup: "css",
        prefix: PREFIX,
        files: [
          {
            destination: "root",
            format: "css/variables",
            filter: (token) => !isThemed(token),
            options: { outputReferences: true, showFileHeader: false },
          },
          {
            destination: "theme",
            format: "css/variables",
            filter: isThemed,
            options: { outputReferences: true, showFileHeader: false },
          },
        ],
      },
    },
  });
}

/** Pulls the declarations out of a `:root { ... }` block. */
const declarations = (css) =>
  css
    .slice(css.indexOf("{") + 1, css.lastIndexOf("}"))
    .trim()
    .split("\n")
    .map((line) => line.trim());

const block = (selector, lines, indent = "") =>
  `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l}`).join("\n")}\n${indent}}`;

async function build() {
  const built = {};
  for (const theme of THEMES) {
    const sd = createDictionary(theme);
    const files = Object.fromEntries(
      (await sd.formatPlatform("css")).map((f) => [f.destination, f.output]),
    );
    const { allTokens } = await sd.getPlatformTokens("css");
    built[theme] = { root: declarations(files.root), theme: declarations(files.theme), allTokens };
  }

  const light = ["color-scheme: light;", ...built.light.theme];
  const dark = ["color-scheme: dark;", ...built.dark.theme];

  const css = [
    "/**\n * Design tokens. Do not edit directly, generated by packages/tokens/build.mjs.\n *\n * Theme with data-theme=\"light|dark\" on <html> (or any subtree).\n * Without it, the user's OS preference decides.\n */",
    block(":root", built.light.root),
    block(':root,\n[data-theme="light"]', light),
    `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', dark, "  ")}\n}`,
    block('[data-theme="dark"]', dark),
    "",
  ].join("\n\n");

  // Metadata for the docs site and JS consumers.
  const darkValues = new Map(built.dark.allTokens.map((t) => [t.name, t.$value ?? t.value]));
  const tokens = built.light.allTokens.map((token) => {
    const original = token.original.$value ?? token.original.value;
    const reference =
      typeof original === "string" && /^\{[^}]+\}$/.test(original)
        ? `--${PREFIX}-${original.slice(1, -1).replaceAll(".", "-")}`
        : undefined;
    const value = token.$value ?? token.value;
    const darkValue = darkValues.get(token.name);
    return {
      name: `--${token.name}`,
      path: token.path,
      tier: isPrimitive(token) ? "primitive" : "semantic",
      type: token.$type ?? token.type,
      value,
      ...(isThemed(token) && darkValue !== value ? { darkValue } : {}),
      ...(reference ? { reference } : {}),
      ...(token.$description ? { description: token.$description } : {}),
    };
  });

  const camel = (name) =>
    name.replace(new RegExp(`^--${PREFIX}-`), "").replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const vars = Object.fromEntries(tokens.map((t) => [camel(t.name), `var(${t.name})`]));

  const js = [
    "// Generated by packages/tokens/build.mjs. Do not edit.",
    "",
    "/** Theme-aware CSS custom property references, e.g. vars.colorPrimarySolid → \"var(--ds-color-primary-solid)\". */",
    `export const vars = ${JSON.stringify(vars, null, 2)};`,
    "",
    "/** Full token metadata (resolved light/dark values, tier, references). */",
    `export const tokens = ${JSON.stringify(tokens, null, 2)};`,
    "",
  ].join("\n");

  const dts = [
    "// Generated by packages/tokens/build.mjs. Do not edit.",
    "",
    `export type TokenName = ${tokens.map((t) => JSON.stringify(t.name)).join(" | ")};`,
    "",
    "export interface Token {",
    "  name: TokenName;",
    "  path: string[];",
    '  tier: "primitive" | "semantic";',
    "  type: string;",
    "  value: string | number;",
    "  darkValue?: string | number;",
    "  reference?: TokenName;",
    "  description?: string;",
    "}",
    "",
    `export declare const vars: {\n${Object.keys(vars)
      .map((k) => `  readonly ${JSON.stringify(k)}: string;`)
      .join("\n")}\n};`,
    "export declare const tokens: Token[];",
    "",
  ].join("\n");

  await mkdir(OUT, { recursive: true });
  await Promise.all([
    writeFile(`${OUT}/tokens.css`, css),
    writeFile(`${OUT}/tokens.json`, JSON.stringify(tokens, null, 2) + "\n"),
    writeFile(`${OUT}/tokens.js`, js),
    writeFile(`${OUT}/tokens.d.ts`, dts),
  ]);

  console.log(`✔ ${tokens.length} tokens → ${OUT}/tokens.{css,js,d.ts,json}`);
}

await build();
